---
# tasks file for ansible-role-nginx-install
- name: Nginx| Update apt cache
  ansible.builtin.apt:
    update_cache: yes

# - name: Nginx | Found pid of process, which occupied port 80
#   shell: "lsof -i :80 -t"
#   register: process_pid
#   changed_when: process_pid.stdout != ""

# - name: Nginx | Kill process, which occupied port 80
#   shell: "kill -9 {{ process_pid.stdout_lines | join(' ') }}"
#   when: process_pid.stdout_lines | length > 0
#   ignore_errors: true


#=============================Stop process occupated port 80========================================================

- name: Nginx | Find PID of process, occupated port 80
  shell: "lsof -i :80 -t | head -n 1"
  register: process_pid
  changed_when: process_pid.stdout != ""

- name: Nginx | Find name of process
  shell: "ps -o comm= -p {{ process_pid.stdout }}"
  register: process_name
  when: process_pid.stdout != ""
  changed_when: false

- name: Nginx | Find systemd-service, appropriate to the process
  shell: "systemctl list-units --type=service --all | grep {{ process_name.stdout }} | awk '{print $1}' | head -n 1"
  register: service_name
  when: process_name.stdout != ""
  changed_when: false

- name: Nginx | Update systemd-service
  systemd:
    name: "{{ service_name.stdout }}"
    state: stopped
  when: service_name.stdout != ""

#=======================================================================================================================

- name: Nginx | Package Install
  apt: 
    name: 
      - nginx
    state: present
  notify: "Start Nginx"

- name: Nginx | Ensure Nginx sites-available and sites-enabled directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled


- name: Copy and render Nginx templates from predefined list
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/sites-available/{{ item }}"
  loop: "{{ nginx_available_configs }}"

- name: Nginx | Remove default symlink from sites-enabled
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Nginx | Remove all symlinks from sites-enabled
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/{{ item }}"
    state: absent
  loop: "{{ nginx_available_configs }}"
  notify: "Reload Nginx"

- name: Nginx | Enable only nginx-load-balancer.conf if load_balancer is true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/nginx-load-balancer.conf"
    dest: "/etc/nginx/sites-enabled/nginx-load-balancer.conf"
    state: link
  when: load_balancer
  notify: "Reload Nginx"

- name: Nginx | Enable all sites except nginx-load-balancer.conf if load_balancer is false
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  loop: "{{ nginx_available_configs }}"
  when: not load_balancer and item != "nginx-load-balancer.conf"
  notify: "Reload Nginx"

- name: Set permanent file descriptor limit
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: "* soft nofile 65536\n* hard nofile 65536"
    regexp: "^\\* (soft|hard) nofile"
    state: present
  become: yes